export const GET_ERRORS = "GET_ERRORS";
export const GET_TODO_TASKS = "GET_TODO_TASKS";
export const GET_TODO_TASK = "GET_TODO_TASK";
export const DELETE_TODO_TASK = "DELETE_TODO_TASK";
export const UPDATE_INLINE_TASK="UPDATE_INLINE_TASK";
export const DELETE_ERROR_TASK="DELETE_ERROR_TASK";